kind: Service
apiVersion: v1
metadata:
  name: k8sweb
  labels:
    name: app-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
  selector:
    app: app-demo
